// Generated by CoffeeScript 2.2.3
(function() {
  var token;

  token = "6baffc80241d5b449708162620d66fa42fcdc86309328f42627bf8610b11fa133d2e407176015f19ddcd8694f618a287c71ed812a6c427253d660d78001826f64963c009202c7a80fb0ef67f298b789c2db03d7d47682aca852b904f205153a31909e4fa3e6842cdf15eba30790e1db7177936bc81cb812dc1648d46449b16c43fc8eda120aabf92ec57509e7b80b2099a49809fc185b7d808fd834fb4dff398";

  require('../index').verify(token, "abcdef").then(function(token) {
    return console.info(token);
  }).catch(function(error) {
    return console.error(error);
  });

}).call(this);

//# sourceMappingURL=verify.js.map
